### ISSUE TITLE
Error on trying to build the development version of eScriptorium

### ISSUE THREAD

**Issue by johnlockejrr** [UB-Mannheim/escriptorium#4]
I tried to build the main dev version of eScriptorium but I got stuck on the final step at installing the frontend:
```
(escriptorium) incognito@DESKTOP-4RGQ03V:~/escriptorium/front$ node --version
v20.11.1
(escriptorium) incognito@DESKTOP-4RGQ03V:~/escriptorium/front$ npm run production
> escriptorium@0.1.0 production
> webpack --config webpack.prod.js

[webpack-cli] Failed to load '/home/incognito/escriptorium/front/webpack.prod.js'
[webpack-cli] Error: Cannot find module 'vue-loader/lib/plugin'
Require stack:
- /home/incognito/escriptorium/front/webpack.common.js
- /home/incognito/escriptorium/front/webpack.prod.js
- /home/incognito/escriptorium/front/node_modules/webpack-cli/lib/webpack-cli.js
- /home/incognito/escriptorium/front/node_modules/webpack-cli/lib/bootstrap.js
- /home/incognito/escriptorium/front/node_modules/webpack-cli/bin/cli.js
- /home/incognito/escriptorium/front/node_modules/webpack/bin/webpack.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (/home/incognito/escriptorium/front/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/incognito/escriptorium/front/webpack.common.js:3:25)
    at Module._compile (/home/incognito/escriptorium/front/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/incognito/escriptorium/front/webpack.common.js',
    '/home/incognito/escriptorium/front/webpack.prod.js',
    '/home/incognito/escriptorium/front/node_modules/webpack-cli/lib/webpack-cli.js',
    '/home/incognito/escriptorium/front/node_modules/webpack-cli/lib/bootstrap.js',
    '/home/incognito/escriptorium/front/node_modules/webpack-cli/bin/cli.js',
    '/home/incognito/escriptorium/front/node_modules/webpack/bin/webpack.js'
  ]
}
```
Which node version should I use? Thanks!

**Comment by stweil** [comment]
One of our installations uses npm 9.8.0 and node v20.5.1, another installation works with npm 10.5.0 and node v21.7.0.

Is vue-loader listed in your package-lock.json, and did you run `npm install`?

**Comment by stweil** [comment]
I suggest to try this installation documentation: https://ub-mannheim.github.io/eScriptorium_Dokumentation/ (German).

**Comment by johnlockejrr** [comment]
I have the public version of eScriptorium running as stand-alone and docker also, just wanted to run this development branch that is different from the public one

**Comment by johnlockejrr** [comment]
> I suggest to try this installation documentation: https://ub-mannheim.github.io/eScriptorium_Dokumentation/ (German).

Thanks for this one, I wasn't aware, I will test eSc with tesseract also, very cool

**Comment by johnlockejrr** [comment]
Wanted to try escriptorium with tesseract as per https://ub-mannheim.github.io/eScriptorium_Dokumentation/eScriptorium-with-tesseract-extension.html
Unfortunately https://github.com/JKamlah/eScriptorium/ doesn't exist anymore :-\

**Comment by stweil** [comment]
cc @JKamlah

**Comment by stweil** [comment]
> Unfortunately https://github.com/JKamlah/eScriptorium/ doesn't exist anymore :-\

Meanwhile it exists again.

**Comment by johnlockejrr** [comment]
Yes, I talked with JKamlah, was private but was kind to make it public.
Thanks for the tip!

**Comment by stweil** [comment]
@johnlockejrr, can this issue be closed?

**Comment by johnlockejrr** [comment]
> [@johnlockejrr](https://github.com/johnlockejrr), can this issue be closed?

Oh yes! :) Is antique.
